# Description:
#  Externs for browser/node/etc APIs.

package(default_visibility = ["//:internal"])

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

closure_js_library(
    name = "externs",
    srcs = [
        "analytics.js",
        "chrome.js",
        "drive.js",
        "node.js",
    ],
)
